# - Try to locate SDL2_image
# This module defines:
#
#  SDL2_IMAGE_INCLUDE_DIR
#  SDL2_IMAGE_LIBRARY
#  SDL2_IMAGE_FOUND
#

FIND_PATH(SDL2_IMAGE_INCLUDE_DIR SDL_image.h 
	HINTS ../SDL2_image SDL2_image
	PATH_SUFFIXES include )

FIND_LIBRARY(SDL2_IMAGE_LIBRARY SDL2_image 
  HINTS $ENV{SDL2DIR} ../SDL2_image SDL2_image
  PATH_SUFFIXES lib64 lib lib/${CMAKE_CXX_LIBRARY_ARCHITECTURE})

IF(SDL2_IMAGE_INCLUDE_DIR AND SDL2_IMAGE_LIBRARY)
	SET(SDL2_IMAGE_FOUND TRUE)
ENDIF(SDL2_IMAGE_INCLUDE_DIR AND SDL2_IMAGE_LIBRARY)

MARK_AS_ADVANCED(SDL2_IMAGE_INCLUDE_DIR SDL2_IMAGE_LIBRARY SDL2_IMAGE_FOUND)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_Image
                                  REQUIRED_VARS SDL2_IMAGE_LIBRARY SDL2_IMAGE_INCLUDE_DIR)