# - Try to locate SDL2_image
# This module defines:
#
#  SDL2_TTF_INCLUDE_DIR
#  SDL2_TTF_LIBRARY
#  SDL2_TTF_FOUND
#

FIND_PATH( SDL2_TTF_INCLUDE_DIR
	SDL_ttf.h 
	HINTS ../SDL2_ttf SDL2_ttf 
	PATH_SUFFIXES include )
	
FIND_LIBRARY(SDL2_TTF_LIBRARY SDL2_ttf 
	HINTS $ENV{SDL2DIR} ../SDL2_ttf SDL2_ttf
	PATH_SUFFIXES lib64 lib lib/${CMAKE_CXX_LIBRARY_ARCHITECTURE})
	

IF(SDL2_TTF_INCLUDE_DIR AND SDL2_TTF_LIBRARY)
	SET(SDL2_TTF_FOUND TRUE)
ENDIF(SDL2_TTF_INCLUDE_DIR AND SDL2_TTF_LIBRARY)


MARK_AS_ADVANCED(SDL2_TTF_INCLUDE_DIR SDL2_TTF_LIBRARY SDL2_TTF_FOUND)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_ttf
                                  REQUIRED_VARS SDL2_TTF_LIBRARY SDL2_TTF_INCLUDE_DIR)
